# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: "single_node_hana"
  variables:
    - group: azure-config-variables
    - group: azure-sap-hana-pipeline-secrets
  pool:
    vmImage: "ubuntu-16.04"
  displayName: "Test deployment of single node hana"
  steps:
  - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
    clean: "all"
    path: "sap-hana"  # path to check out source code, relative to the agent's build directory
    persistCredentials: boolean  # set to 'true' to leave the OAuth token in the Git config after the initial fetch
  - script: |
      ssh-keygen -b 4096 -t rsa -f /tmp/sshkey -q -N ""
      cp deploy/vm/test/terraform.tfvars deploy/vm/modules/single_node_hana
      cd deploy/vm/modules/single_node_hana
      terraform init
      terraform apply -no-color -auto-approve
      echo "terraform apply succeeded. Now running terraform destroy"
      terraform destroy -no-color -auto-approve
    displayName: 'Test single node hana'
    env:
      TF_VAR_azure_service_principal_id: $(hana-pipeline-spn-id)
      TF_VAR_azure_service_principal_pw: $(hana-pipeline-spn-pw)
      TF_VAR_url_sap_sapcar_linux: $(hana-int-sapcar-721-linux)
      TF_VAR_url_sap_hdbserver: $(hana-int-hana2sps03-server)
      TF_VAR_url_hana_studio_linux: $(hana-int-hanastudio-linux)
      TF_VAR_pw_db_system: $(hana-int-pw-db-system)
      TF_VAR_pw_os_sidadm: $(hana-int-pw-sid-adm)
      TF_VAR_pw_os_sapadm: $(hana-int-pw-sap-adm)
      TF_VAR_pw_hacluster: $(hana-int-pw-sap-adm)
      AZURE_CLIENT_ID: $(hana-pipeline-spn-id)
      AZURE_SECRET: $(hana-pipeline-spn-pw)
      AZURE_TENANT: $(landscape-tenant)
      AZURE_SUBSCRIPTION_ID: $(landscape-subscription)
      ARM_CLIENT_ID: $(hana-pipeline-spn-id)
      ARM_CLIENT_SECRET: $(hana-pipeline-spn-pw)
      ARM_TENANT_ID: $(landscape-tenant)
      ARM_SUBSCRIPTION_ID: $(landscape-subscription)